# Generated by Django 5.2.8 on 2025-11-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fims_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['id']},
        ),
        migrations.AddIndex(
            model_name='corpadmin',
            index=models.Index(fields=['company'], name='idx_corpadmin_company'),
        ),
        migrations.AddIndex(
            model_name='corpadmin',
            index=models.Index(fields=['email'], name='idx_corpadmin_email'),
        ),
        migrations.AddIndex(
            model_name='locadmin',
            index=models.Index(fields=['company'], name='idx_locadmin_company'),
        ),
        migrations.AddIndex(
            model_name='locadmin',
            index=models.Index(fields=['location'], name='idx_locadmin_location'),
        ),
        migrations.AddIndex(
            model_name='locadmin',
            index=models.Index(fields=['email'], name='idx_locadmin_email'),
        ),
        migrations.AddConstraint(
            model_name='corpadmin',
            constraint=models.UniqueConstraint(fields=('company', 'email'), name='uniq_corp_admin_email_per_company'),
        ),
        migrations.AddConstraint(
            model_name='locadmin',
            constraint=models.UniqueConstraint(fields=('location', 'email'), name='uniq_loc_admin_email_per_location'),
        ),
    ]
