# Generated by Django 5.2.9 on 2025-12-05 15:21

import core.models.user_fields_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fims_core', '0002_alter_continent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpadmin',
            name='uid_expiry_date',
            field=models.DateTimeField(default=core.models.user_fields_mixin._default_uid_expiry),
        ),
        migrations.AddField(
            model_name='locadmin',
            name='uid_expiry_date',
            field=models.DateTimeField(default=core.models.user_fields_mixin._default_uid_expiry),
        ),
        migrations.AddField(
            model_name='locationuser',
            name='uid_expiry_date',
            field=models.DateTimeField(default=core.models.user_fields_mixin._default_uid_expiry),
        ),
    ]
